### ISSUE TITLE
mpd fails to build with latest glibc 2.30

### ISSUE THREAD

**Issue by david-geiger** [MusicPlayerDaemon/MPD#630]
Hi,

I tried to build latest mpd release (0.21.14) on Mageia Cauldron, but it fails against latest glibc 2.30 with:

> /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
../src/output/plugins/SolarisOutputPlugin.cxx:25:10: fatal error: sys/stropts.h: No such file or directory
 #include <sys/stropts.h>
          ^~~~~~~~~~~~~~~
compilation terminated.

If I remove the #include <sys/stropts.h> now it fails with:

> /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
../src/output/plugins/SolarisOutputPlugin.cxx: In member function 'virtual void SolarisOutput::Cancel()':
../src/output/plugins/SolarisOutputPlugin.cxx:144:18: error: 'I_FLUSH' was not declared in this scope; did you mean 'CFLUSH'?
  144 |  ioctl(fd.Get(), I_FLUSH);
      |                  ^~~~~~~
      |                  CFLUSH

Regards,
David

**Comment by MaxKellermann** [comment]
Mageia, that's Linux, not Solaris. Why did you enable the Solaris output plugin on Linux? It's disabled by default on Linux.

**Comment by MaxKellermann** [comment]
Fixed in 818b7e0641f25f55c46bf654d8edb7911c10d584, for those people (other than me) who insist on building the Solaris plugin on Linux.

**Comment by david-geiger** [comment]
I don't know why it is enable on linux, but we haven't enable it manually or something else.

Let's try your fix!

**Comment by MaxKellermann** [comment]
If it was auto-enabled on Linux, that would be another bug.
(Note that `-Dauto_features=enabled` qualifies as "enabling the Solaris plugin explicitly".)

**Comment by david-geiger** [comment]
So ok now! mpd successful built, many thanks...
