### ISSUE TITLE
fmtlib 12.2.0: error: 'format' is not a member of 'fmt'

### ISSUE THREAD

**Issue by 0-wiz-0** [MusicPlayerDaemon/MPD#2524]
### Describe the bug
After updating fmtlib in pkgsrc to 12.2.0, mpd stopped building.
We have 0.24.8, but updating to 0.24.12 doesn't fix it.

## Expected Behavior
Build succeeds.

## Actual Behavior
```
73/600] Compiling C++ object src/net/libnet.a.p/ToString.cxx.o
FAILED: [code=1] src/net/libnet.a.p/ToString.cxx.o
c++ -Isrc/net/libnet.a.p -Isrc/net -I../src/net -Isrc -I../src -I. -I.. -I/usr/pkg/include -I/usr/include -I/usr/pkg/include/libxml2 -I/usr/pkg/include/ffmpeg7 -I/usr/pkg/include/freetype2 -I/usr/pkg/include/libdrm -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++20 -ffast-math -ftree-vectorize -Wcast-qual -Wdouble-promotion -Wmissing-declarations -Wshadow -Wunused -Wvla -Wwrite-strings -Wno-stringop-overflow -fno-threadsafe-statics -fmerge-all-constants -Wcomma-subscript -Wextra-semi -Wmismatched-tags -Woverloaded-virtual -Wsign-promo -Wsuggest-override -Wvolatile -Wvirtual-inheritance -Wno-missing-field-initializers -Wno-non-virtual-dtor -fvisibility=hidden -ffunction-sections -fdata-sections -D_GNU_SOURCE -O2 -g -fstack-clash-protection -g -fPIC -Wno-array-bounds -MD -MQ src/net/libnet.a.p/ToString.cxx.o -MF src/net/libnet.a.p/ToString.cxx.o.d -o src/net/libnet.a.p/ToString.cxx.o -c ../src/net/ToString.cxx
../src/net/ToString.cxx: In function 'std::string ToString(SocketAddress)':
../src/net/ToString.cxx:80:37: error: 'format' is not a member of 'fmt'
   80 |                         return fmt::format("[{}]:{}", host, serv);
      |                                     ^~~~~~
../src/net/ToString.cxx:84:29: error: 'format' is not a member of 'fmt'
   84 |                 return fmt::format("{}:{}", host, serv);
      |                             ^~~~~~
```

## Version
mpd 0.24.12

## Configuration
n/a

## Log

see above

**Comment by MaxKellermann** [comment]
I suppose this was fixed by https://github.com/MusicPlayerDaemon/MPD/pull/2512 (not yet released)

**Comment by 0-wiz-0** [comment]
Thank you, that patch does fix the build for me.
