### ISSUE TITLE
Doesn't build with libcdio 1.1.0

### ISSUE THREAD

**Issue by marillat** [MusicPlayerDaemon/MPD#173]
cdio_list_free() now uses three parameters (was two ln 1.0.0).
https://www.gnu.org/software/libcdio/doxygen/ds_8h.html
````
src/archive/plugins/Iso9660ArchivePlugin.cxx:118:32: error: too few arguments to function 'void _cdio_list_free(CdioList_t*, int, CdioDataFree_t)'
  _cdio_list_free (entlist, true);
                                ^
In file included from /usr/include/cdio/iso9660.h:40:0,
                 from src/archive/plugins/Iso9660ArchivePlugin.cxx:34:
/usr/include/cdio/ds.h:46:6: note: declared here
 void _cdio_list_free (CdioList_t *p_list, int free_data, CdioDataFree_t free_fn);
      ^~~~~~~~~~~~~~~
Makefile:7961: recipe for target 'src/archive/plugins/libarchive_a-Iso9660ArchivePlugin.o' failed
````

**Comment by MaxKellermann** [comment]
WTF, an API breakage in a library minor release, and this isn't even mentioned in the changelog: http://git.savannah.gnu.org/cgit/libcdio.git/tree/NEWS?h=release-1.1.0

**Comment by MaxKellermann** [comment]
And this is the git commit which broke API compatibility: http://git.savannah.gnu.org/cgit/libcdio.git/commit/?id=73800fc0cd81a735764f79b7f3f957d8a71eb02c

No API documentation, no changelog update. And the commit adds 5 `goto`s. In 2017. Serious code WTF.

**Comment by MaxKellermann** [comment]
This will be postponed until the libcdio project adds API documentation explaining application developers what to do. Until that happens, MPD is officially incompatible with this new libcdio release.

**Comment by marillat** [comment]
I filled a bug https://savannah.gnu.org/bugs/index.php?52690

**Comment by rocky** [comment]
With 1.1.0 new types were added for list of files returned reading a directory and a new type for a list of directories. Freeing generic lists of things created memory leaks when the individual items had dynamically allocated data because that data wasn't freed. As a result, the list free routine needed added an extra parameter: the function to call to free an item in the list. 

So for that specific error, I believe what you'd do is change the type of the [entlist](https://github.com/MusicPlayerDaemon/MPD/blob/master/src/archive/plugins/Iso9660ArchivePlugin.cxx#L94) to a `CdioISO9660FileList_t` and call [iso9660_stat_free](https://www.gnu.org/software/libcdio/doxygen/iso9660_8h.html#a0ed4d724b9494203c379d80bcda01c10) on [line 118](https://github.com/MusicPlayerDaemon/MPD/blob/master/src/archive/plugins/Iso9660ArchivePlugin.cxx#L118) instead. 

If there are other places that work with file lists and directory lists, they should be changed as well.

As for warning of breakage, libcdio now uses semantic versioning. This means that whenever there is a change in the major or the minor version there is an API change. 

In advance of a release, I post to https://lists.gnu.org/mailman/listinfo/libcdio-devel where you can get release candidate tarballs, invite people to test them out, and give feedback. So perhaps @MaxKellermann should subscribe to that mailing list, test out the release candidates, and give feedback at the time when it has the most impact and is easiest to change.

As for the goto's, those are basically error exits to make sure dynamically allocated data gets freed properly. Without that I think you'd have to write something like `free(a); free(b); free(c); return` all of the places where you want to return from a function without going to the end. Or write custom functions or C preprocessor macros which do that. If people have a better way to do this without all of the repetition, feel free to post patches at https://savannah.gnu.org/patch/?group=libcdio

Likewise if there is documentation that is missing. 

libcdio is free software. I haven never gotten any revenue (nor fame) in writing this and frankly don't have much use for it either anymore.  See https://www.gnu.org/software/libcdio/libcdio.html#History for why I even undertook to write this.

 Many of the projects like this one I have no knowledge of until there is a problem. You can bitch and moan about the sorry state of the project, its code and documentation. Or you can contribute to it, make it better, and fix its problems.

**Comment by MaxKellermann** [comment]
The libcdio project may be in a bad state, but that is not my responsibility, because I am not at all interested in that library. It just happens that somebody wrote a plugin for MPD using this library 7 years ago and dropped his code, and now I'm responsible for maintaining that guy's code. But I've never used this plugin, and I never will - none of my computers has a CD drive these days. True, I've never tested the code that I maintain.
Sure you can say "send a patch" for whatever's wrong with your project, and I would certainly do that with enough interest and time, but I have neither (and I send lots of patches to lots of projects I'm interested in). Nor do I have time to read your mailing list or test your release candidates and give feedback.
And so @rocky you take sole responsibility for the quality of libcdio releases or its lack documentation, and I have the right to criticize that quality. Just as anybody else can criticize the quality of MPD releases.

Apart from questions of taste (e.g. whether `goto` is a good way to recover from errors) you made a huge mistake in your 1.1.0 release by breaking ABI compatibility without increasing the SO version. This will cause random crashes in applications. This is one of the things a shared library must never ever do. And this is serious enough to justify taking the release down as quickly as possible, before distributions pick it up. Be quick!

**Comment by rocky** [comment]
> And this is serious enough to justify taking the release down as quickly as possible, before distributions pick it up. 

Nope. We move forward not backward.

**Comment by MaxKellermann** [comment]
It scares me that you as a maintainer of a shared library reject this important responsibility of yours.
It scares me enough to consider removing the plugin from MPD, because I don't want all the bug reports about MPD crashes caused by this libcdio mistake.

**Comment by kingosticks** [comment]
The [Semantic versioning website](https://semver.org/) is really clear about when to change the major version:
> MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.

I don't have a horse in this race but your breaking change clearly needed a new MAJOR version.

**Comment by rocky** [comment]
Ok. Will put out a release to change Major.

**Comment by MaxKellermann** [comment]
Nooo! This has **nothing** to do with libcdio's release version number. You can give it any number you want, in any scheme, as long as they increase - the rest is a matter of taste.
This is about the SO version.

**Comment by rocky** [comment]
When I change the version number, I'll look at the SO versions as well. I may make a mistake there as well, so I suggest people follow along.
