### ISSUE TITLE
RoarOutputPlugin.cxx doesn't compile on Ubuntu 18.10

### ISSUE THREAD

**Issue by klassikmann** [MusicPlayerDaemon/MPD#377]
On Ubuntu 18.10 mpd-0.20.22 and mpd-0.20.21 do not compile  with
#define ENABLE_ROAR 1

On Ubuntu 18.04: no problem making 0.20.21

Log:
g++ -DHAVE_CONFIG_H -I.  -DNDEBUG -I./src -I/usr/include -DSYSTEM_CONFIG_FILE_LOCATION='"/usr/local/etc/mpd.conf"'  -I/usr/include/alsa   -I/usr/include/AL  -D_REENTRANT  -pthread -D_GNU_SOURCE -pthread -g -O2 -fvisibility=hidden -fno-threadsafe-statics -fmerge-all-constants -ffast-math -ftree-vectorize -ffunction-sections -fdata-sections -Wall -Wextra -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wsign-compare -Wno-noexcept-type -MT src/output/plugins/liboutput_plugins_a-RoarOutputPlugin.o -MD -MP -MF src/output/plugins/.deps/liboutput_plugins_a-RoarOutputPlugin.Tpo -c -o src/output/plugins/liboutput_plugins_a-RoarOutputPlugin.o `test -f 'src/output/plugins/RoarOutputPlugin.cxx' || echo './'`src/output/plugins/RoarOutputPlugin.cxx
In file included from /usr/include/libroar/libroar.h:173,
                 from /usr/include/roaraudio.h:133,
                 from src/output/plugins/RoarOutputPlugin.cxx:36:
/usr/include/libroar/vio_stdio.h:50:46: error: ‘_IO_off64_t’ has not been declared
 int roar_vio_to_stdio_lseek (void *__cookie, _IO_off64_t *__pos, int __w);

Workaround:
Disabling ROAR if not needed.

**Comment by MaxKellermann** [comment]
This is a libroar bug.
