### ISSUE TITLE
mpd 0.23.15 does not build with icu 76.1 (missing -licuuc in test_ldflags)

### ISSUE THREAD

**Issue by 13ilya** [MusicPlayerDaemon/MPD#2151]
### Describe the bug
Updated icu to 76.1 and discovered that mpd cannot compile.

## Expected Behavior
Package compiles successfully.

## Actual Behavior
https://build.opensuse.org/package/show/openSUSE:Factory/mpd
https://build.opensuse.org/package/live_build_log/openSUSE:Factory/mpd/standard/x86_64
```
[  100s] /usr/lib64/gcc/x86_64-suse-linux/14/../../../../x86_64-suse-linux/bin/ld: /tmp/cck0AZO9.ltrans6.ltrans.o: undefined reference to symbol 'ucnv_fromUnicode_76'
[  100s] /usr/lib64/gcc/x86_64-suse-linux/14/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libicuuc.so.76: error adding symbols: DSO missing from command line
[  100s] collect2: error: ld returned 1 exit status
[  100s] ninja: build stopped: subcommand failed.
```
