### ISSUE TITLE
Please add support for ffmpeg-5.1

### ISSUE THREAD

**Issue by leigh123linux** [MusicPlayerDaemon/MPD#1582]
## Feature request
Please add support for ffmpeg-5.1, it currently fails to compile.

```
FAILED: mpd 
g++  -o mpd mpd.p/meson-generated_.._GitVersion.cxx.o mpd.p/src_Main.cxx.o mpd.p/src_protocol_ArgParser.cxx.o mpd.p/src_command_CommandError.cxx.o mpd.p/src_command_PositionArg.cxx.o mpd.p/src_command_AllCommands.cxx.o mpd.p/src_command_QueueCommands.cxx.o mpd.p/src_command_TagCommands.cxx.o mpd.p/src_command_PlayerCommands.cxx.o mpd.p/src_command_PlaylistCommands.cxx.o mpd.p/src_command_FileCommands.cxx.o mpd.p/src_command_OutputCommands.cxx.o mpd.p/src_command_MessageCommands.cxx.o mpd.p/src_command_ClientCommands.cxx.o mpd.p/src_command_PartitionCommands.cxx.o mpd.p/src_command_OtherCommands.cxx.o mpd.p/src_command_CommandListBuilder.cxx.o mpd.p/src_Idle.cxx.o mpd.p/src_IdleFlags.cxx.o mpd.p/src_decoder_Thread.cxx.o mpd.p/src_decoder_Control.cxx.o mpd.p/src_decoder_Bridge.cxx.o mpd.p/src_decoder_DecoderPrint.cxx.o mpd.p/src_client_Listener.cxx.o mpd.p/src_client_Client.cxx.o mpd.p/src_client_Config.cxx.o mpd.p/src_client_Domain.cxx.o mpd.p/src_client_Event.cxx.o mpd.p/src_client_Expire.cxx.o mpd.p/src_client_Idle.cxx.o mpd.p/src_client_List.cxx.o mpd.p/src_client_New.cxx.o mpd.p/src_client_Process.cxx.o mpd.p/src_client_Read.cxx.o mpd.p/src_client_Write.cxx.o mpd.p/src_client_Message.cxx.o mpd.p/src_client_Subscribe.cxx.o mpd.p/src_client_File.cxx.o mpd.p/src_client_Response.cxx.o mpd.p/src_client_ThreadBackgroundCommand.cxx.o mpd.p/src_Listen.cxx.o mpd.p/src_LogInit.cxx.o mpd.p/src_ls.cxx.o mpd.p/src_Instance.cxx.o mpd.p/src_MusicBuffer.cxx.o mpd.p/src_MusicPipe.cxx.o mpd.p/src_MusicChunk.cxx.o mpd.p/src_MusicChunkPtr.cxx.o mpd.p/src_Mapper.cxx.o mpd.p/src_Partition.cxx.o mpd.p/src_Permission.cxx.o mpd.p/src_player_CrossFade.cxx.o mpd.p/src_player_Thread.cxx.o mpd.p/src_player_Control.cxx.o mpd.p/src_PlaylistError.cxx.o mpd.p/src_PlaylistPrint.cxx.o mpd.p/src_PlaylistSave.cxx.o mpd.p/src_playlist_PlaylistStream.cxx.o mpd.p/src_playlist_PlaylistMapper.cxx.o mpd.p/src_playlist_PlaylistAny.cxx.o mpd.p/src_playlist_PlaylistSong.cxx.o mpd.p/src_playlist_PlaylistQueue.cxx.o mpd.p/src_playlist_Print.cxx.o mpd.p/src_db_PlaylistVector.cxx.o mpd.p/src_queue_Queue.cxx.o mpd.p/src_queue_QueuePrint.cxx.o mpd.p/src_queue_QueueSave.cxx.o mpd.p/src_queue_Playlist.cxx.o mpd.p/src_queue_PlaylistControl.cxx.o mpd.p/src_queue_PlaylistEdit.cxx.o mpd.p/src_queue_PlaylistTag.cxx.o mpd.p/src_queue_PlaylistState.cxx.o mpd.p/src_ReplayGainGlobal.cxx.o mpd.p/src_LocateUri.cxx.o mpd.p/src_SongUpdate.cxx.o mpd.p/src_SongLoader.cxx.o mpd.p/src_SongPrint.cxx.o mpd.p/src_SongSave.cxx.o mpd.p/src_StateFile.cxx.o mpd.p/src_StateFileConfig.cxx.o mpd.p/src_Stats.cxx.o mpd.p/src_TagPrint.cxx.o mpd.p/src_TagSave.cxx.o mpd.p/src_TagFile.cxx.o mpd.p/src_TagStream.cxx.o mpd.p/src_TagAny.cxx.o mpd.p/src_TimePrint.cxx.o mpd.p/src_mixer_Volume.cxx.o mpd.p/src_PlaylistFile.cxx.o mpd.p/src_CommandLine.cxx.o mpd.p/src_unix_SignalHandlers.cxx.o mpd.p/src_unix_Daemon.cxx.o mpd.p/src_queue_PlaylistUpdate.cxx.o mpd.p/src_command_StorageCommands.cxx.o mpd.p/src_command_DatabaseCommands.cxx.o mpd.p/src_RemoteTagCache.cxx.o mpd.p/src_command_StickerCommands.cxx.o mpd.p/src_sticker_Database.cxx.o mpd.p/src_sticker_Print.cxx.o mpd.p/src_sticker_SongSticker.cxx.o mpd.p/src_command_NeighborCommands.cxx.o mpd.p/src_TagArchive.cxx.o mpd.p/src_db_update_Archive.cxx.o -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 -Wl,-dT,/builddir/build/BUILD/mpd-0.23.8/.package_note-mpd-0.23.8-2.fc37.x86_64.ld -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wl,--start-group libbasic.a src/config/libfs.a liblog.a src/fs/libfs.a src/lib/zlib/libzlib.a src/io/libio.a src/system/libsystem.a src/lib/icu/libicu.a src/util/libutil.a src/lib/dbus/libdbus.a src/event/libevent.a src/io/uring/liburing.a src/thread/libthread.a src/net/libnet.a src/neighbor/libneighbor_glue.a src/neighbor/plugins/libneighbor_plugins.a src/lib/upnp/libupnp.a src/lib/curl/libcurl.a src/lib/expat/libexpat.a src/input/libinput_glue.a src/input/plugins/libinput_plugins.a src/lib/alsa/libalsa.a src/lib/ffmpeg/libffmpeg.a src/lib/nfs/libnfs.a src/lib/yajl/libyajl.a src/lib/crypto/libcrypto_md5.a src/input/libinput_api.a src/pcm/libpcm.a src/pcm/libpcm_basic.a src/tag/libtag.a src/time/libtime.a src/archive/libarchive_glue.a src/archive/plugins/libarchive_plugins.a src/archive/libarchive_api.a src/output/liboutput_glue.a src/filter/libfilter_glue.a src/filter/plugins/libfilter_plugins.a src/filter/libfilter_api.a src/mixer/plugins/libmixer_plugins.a src/lib/pulse/libpulse.a src/output/plugins/liboutput_plugins.a src/lib/pipewire/libpipewire.a src/output/liboutput_api.a src/zeroconf/libzeroconf_bonjour.a src/zeroconf/avahi/libavahi.a src/mixer/libmixer_glue.a src/decoder/libdecoder_glue.a src/decoder/plugins/libdecoder_plugins.a src/lib/xiph/libflac.a src/lib/xiph/libxiph.a src/lib/xiph/libvorbis.a src/lib/xiph/libogg.a src/lib/crypto/libcrypto_base64.a src/decoder/libdecoder_api.a src/encoder/libencoder_glue.a src/encoder/plugins/libencoder_plugins.a src/playlist/libplaylist_glue.a src/playlist/plugins/libplaylist_plugins.a src/playlist/libplaylist_api.a src/db/libdb_glue.a src/db/plugins/libdb_plugins.a src/lib/pcre/libpcre.a src/db/libdb_api.a src/storage/libstorage_api.a src/storage/libstorage_glue.a src/storage/plugins/libstorage_plugins.a src/song/libsong.a src/lib/systemd/libsystemd.a src/lib/sqlite/libsqlite.a /usr/lib64/libdbus-1.so /usr/lib64/liburing.so /usr/lib64/libfmt.so /usr/lib64/libavformat.so /usr/lib64/libavcodec.so /usr/lib64/libavfilter.so /usr/lib64/libavutil.so /usr/lib64/libyajl.so /usr/lib64/libpcre2-8.so /usr/lib64/libsqlite3.so /usr/lib64/libz.so /usr/lib64/libicui18n.so /usr/lib64/libicuuc.so /usr/lib64/libicudata.so -pthread /usr/lib64/libupnp.so /usr/lib64/libixml.so /usr/lib64/libcurl.so /usr/lib64/libexpat.so /usr/lib64/libcdio_paranoia.so /usr/lib64/libcdio_cdda.so /usr/lib64/libcdio.so -lm /usr/lib64/libmms.so /usr/lib64/libnfs.so /usr/lib64/libasound.so /usr/lib64/libsamplerate.so /usr/lib64/libsoxr.so -lid3tag -lbz2 /usr/lib64/libiso9660.so /usr/lib64/libzzip.so /usr/lib64/libpulse.so /usr/lib64/libao.so /usr/lib64/libjack.so /usr/lib64/libpipewire-0.3.so /usr/lib64/libshout.so /usr/lib64/libopenal.so /usr/lib64/libavahi-common.so /usr/lib64/libavahi-client.so /usr/lib64/libFLAC.so /usr/lib64/libfluidsynth.so /usr/lib64/libaudiofile.so -lfaad -lmad /usr/lib64/libmikmod.so /usr/lib64/libmodplug.so /usr/lib64/libopenmpt.so /usr/lib64/libmpg123.so /usr/lib64/libopus.so /usr/lib64/libsidplayfp.so /usr/lib64/libsndfile.so /usr/lib64/libogg.so /usr/lib64/libvorbis.so /usr/lib64/libwavpack.so /usr/lib64/libWildMidi.so /usr/lib64/libvorbisenc.so -lmp3lame /usr/lib64/libtwolame.so /usr/lib64/libmpdclient.so /usr/lib64/libsystemd.so -Wl,--end-group
/usr/bin/ld: /tmp/cc5m0C7i.ltrans15.ltrans.o: in function `ffmpeg_scan_stream(InputStream&, TagHandler&) [clone .lto_priv.0]':
/builddir/build/BUILD/mpd-0.23.8/redhat-linux-build/../src/decoder/plugins/FfmpegIo.cxx:31: undefined reference to `av_free(void*)'
/usr/bin/ld: /tmp/cc5m0C7i.ltrans15.ltrans.o:/builddir/build/BUILD/mpd-0.23.8/redhat-linux-build/../src/decoder/plugins/FfmpegIo.cxx:32: undefined reference to `av_free(void*)'
/usr/bin/ld: /tmp/cc5m0C7i.ltrans15.ltrans.o: in function `ffmpeg_decode(DecoderClient&, InputStream&) [clone .lto_priv.0]':
/builddir/build/BUILD/mpd-0.23.8/redhat-linux-build/../src/decoder/plugins/FfmpegIo.cxx:31: undefined reference to `av_free(void*)'
/usr/bin/ld: /tmp/cc5m0C7i.ltrans15.ltrans.o:/builddir/build/BUILD/mpd-0.23.8/redhat-linux-build/../src/decoder/plugins/FfmpegIo.cxx:32: undefined reference to `av_free(void*)'
/usr/bin/ld: /tmp/cc5m0C7i.ltrans15.ltrans.o: in function `ffmpeg_decode(DecoderClient&, InputStream&) [clone .lto_priv.0]':
/builddir/build/BUILD/mpd-0.23.8/redhat-linux-build/../src/decoder/plugins/FfmpegIo.cxx:31: undefined reference to `av_free(void*)'
/usr/bin/ld: /tmp/cc5m0C7i.ltrans15.ltrans.o:/builddir/build/BUILD/mpd-0.23.8/redhat-linux-build/../src/decoder/plugins/FfmpegIo.cxx:32: more undefined references to `av_free(void*)' follow
/usr/bin/ld: /tmp/cc5m0C7i.ltrans23.ltrans.o: in function `AvioStream::Open() [clone .constprop.0]':
/builddir/build/BUILD/mpd-0.23.8/redhat-linux-build/../src/decoder/plugins/FfmpegIo.cxx:102: undefined reference to `av_malloc(unsigned long)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by MaxKellermann** [comment]
This problem was caused by commit ebae25d175eb31fbbadf8b0b2d079915ad40396d (https://github.com/MusicPlayerDaemon/MPD/pull/1466) @dankamongmen

**Comment by dankamongmen** [comment]
This looks possibly like it needs some `extern "C" {` love somewhere...i can take a look at it in a day or two if needed.

**Comment by dankamongmen** [comment]
hah, yep it looks like it was =] nice work

**Comment by leigh123linux** [comment]
Thanks for fixing it.
