### ISSUE TITLE
clang-5.0 build error AdPlugDecoderPlugin

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/MPD#202]
Debian testing, MPD from git master, x_64, clang-5.0, clang++-5.0 

./configure CC=clang-5.0 CXX=clang++-5.0

src/decoder/plugins/AdPlugDecoderPlugin.cxx:137:2: error: target exception
      specification is not superset of source
        adplug_scan_file,

Works with gcc 7.2.0 ./configure CC=gcc CXX=g++
