### ISSUE TITLE
Compile error on macOS

### ISSUE THREAD

**Issue by dhocker** [MusicPlayerDaemon/MPD#1232]
### Describe the bug
The HEAD version of the MPD repo generates the following error when compiling on macOS Big Sur 10.15.2.

[486/583] Compiling C++ object mpd.p/src_command_FileCommands.cxx.o
FAILED: mpd.p/src_command_FileCommands.cxx.o 
c++ -Impd.p -I. -I../.. -Isrc -I../../src -I/usr/local/include -I/usr/local/Cellar/fmt/7.1.3/include -I/usr/local/Cellar/ffmpeg/4.4_1/include -I/usr/local/Cellar/pcre/8.44/include -Xclang -fcolor-diagnostics -DNDEBUG -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O2 -g -ffast-math -ftree-vectorize -Wcast-qual -Wdouble-promotion -Wmissing-declarations -Wshadow -Wunused -Wvla -Wwrite-strings -Wunreachable-code-aggressive -Wused-but-marked-unused -fno-threadsafe-statics -fmerge-all-constants -Wextra-semi -Wmismatched-tags -Woverloaded-virtual -Wsign-promo -Wno-non-virtual-dtor -Wcomma -Wheader-hygiene -Winconsistent-missing-destructor-override -Wsuggest-override -fvisibility=hidden -ffunction-sections -fdata-sections -D_GNU_SOURCE -DBOOST_ALL_NO_LIB -MD -MQ mpd.p/src_command_FileCommands.cxx.o -MF mpd.p/src_command_FileCommands.cxx.o.d -o mpd.p/src_command_FileCommands.cxx.o -c ../../src/command/FileCommands.cxx
../../src/command/FileCommands.cxx:159:36: error: no viable constructor or deduction guide for deduction of template arguments of 'array'
        static constexpr auto art_names = std::array {
                                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:219:64: note: candidate function template not viable: requires 1 argument, but 4 were provided
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:219:64: note: candidate function template not viable: requires 0 arguments, but 4 were provided
1 error generated.
[495/583] Compiling C++ object mpd.p/src_command_OtherCommands.cxx.o
ninja: build stopped: subcommand failed.

OS:
macOS 10.15.2
architecture x86_64

CLang reports the following version info:
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

This error appears to have been introduced by commit 30e3ef4c8ee9c0dd78a50e2c4489529381f7c137. As an aside, there appears to be at least one other instance of the same error in src/sticker/Database.cxx. However, the build never reaches that file.

I made a number of attempts at fixing the error, but it's been more than 10 years since I've worked in C++. If someone comes up with a fix, I'll be glad to test compile it on macOS.

## Expected Behavior
Clean compile.

## Actual Behavior
Compile time error.

## Version

This is the github version:
v0.22.10-474-gbedcf1cce

## Log

Not available.

**Comment by dhocker** [comment]
To get around this build error, I went back to commit 46600931e432b4b504e5338bcc4eb3dd56210b96. This commit builds without error on macOS.

**Comment by dhocker** [comment]
Here is a reference to another project that experienced the same kind of compile error: [reference](https://github.com/deepmind/open_spiel/issues/490).

**Comment by dhocker** [comment]
It turns out that the problem is a missing #include <array> statement. This line needs to be inserted in src/sticker/Database.cxx after line 30 and src/command/FileCommands.cxx after line 51.

**Comment by MaxKellermann** [comment]
18be8c3318a89b58762bef8cdfaa6d8c01df5b4d
