### ISSUE TITLE
0.20.7: build problem on debian 8.8 (armbian)

### ISSUE THREAD

**Issue by Warter21** [MusicPlayerDaemon/MPD#45]
It works fine with 0.20.6.

-----------------------------------------------------------------------------------------------------------
g++ -std=c++14 -DHAVE_CONFIG_H -I.  -DNDEBUG -I./src -I/usr/include -DSYSTEM_CONFIG_FILE_LOCATION='"/etc/mpd.conf"' -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -pthread -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -fvisibility=hidden -fno-threadsafe-statics -fmerge-all-constants -ffast-math -ftree-vectorize -ffunction-sections -fdata-sections -Wall -Wextra -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wsign-compare -c -o src/Main.o src/Main.cxx
src/Main.cxx:125:23: error: call to non-constexpr function ‘const _Tp& std::max(const _Tp&, const _Tp&) [with _Tp = unsigned int]’
          64 * KILOBYTE);
                       ^
Makefile:14259: recipe for target 'src/Main.o' failed
make[3]: *** [src/Main.o] Error 1
make[3]: Leaving directory '/usr/src/mpdcomp/mpd-0.20.7'
Makefile:4669: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/usr/src/mpdcomp/mpd-0.20.7'
dh_auto_build: make -j1 returned exit code 2
debian/rules:145: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory '/usr/src/mpdcomp/mpd-0.20.7'
debian/rules:128: recipe for target 'binary' failed
make: *** [binary] Error 2
debuild: fatal error at line 1352:
couldn't exec debian/rules:

**Comment by MaxKellermann** [comment]
This is a bug in your old GCC version, which wasworked around today in 64786ec12a6e648bf64d2e7e76772cf0d2029487

**Comment by norrest** [comment]
apt-get install gcc
Reading package lists... Done
Building dependency tree
Reading state information... Done
gcc is already the newest version.

**Comment by MaxKellermann** [comment]
@norrest what is it you want to tell us with this meaningless paste?

**Comment by ArchangeGabriel** [comment]
@MaxKellermann I guess @norrest is trying to say that is GCC is up-to-date (w.r.t. the distro provided one), but what they might not understand is that it’s the version of GCC provided by their distro that is outdated, because that is a stable distribution.
