### ISSUE TITLE
0.20.7 build failure on macOS: error: target exception specification is not superset of source

### ISSUE THREAD

**Issue by ilovezfs** [MusicPlayerDaemon/MPD#44]
0.20.7 fails to build on macOS (tested on 10.10, 10.11, and 10.12).

Build logs here:
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1419/version=sierra/console
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1419/version=el_capitan/console
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1419/version=yosemite/console

The error is
```
clang++ -std=c++14 -DHAVE_CONFIG_H -I.  -DNDEBUG -I./src -I/usr/local/include -DSYSTEM_CONFIG_FILE_LOCATION='"/usr/local/etc/mpd.conf"'           -Qunused-arguments -pthread -g -O2 -fvisibility=hidden -fno-threadsafe-statics -fmerge-all-constants -ffast-math -ftree-vectorize -ffunction-sections -fdata-sections -Wall -Wextra -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wsign-compare -c -o src/output/plugins/liboutput_plugins_a-OSXOutputPlugin.o `test -f 'src/output/plugins/OSXOutputPlugin.cxx' || echo './'`src/output/plugins/OSXOutputPlugin.cxx
src/output/plugins/OSXOutputPlugin.cxx:690:2: error: target exception specification is not superset of source
        osx_output_delay,
        ^
1 error generated.
make[1]: *** [src/output/plugins/liboutput_plugins_a-OSXOutputPlugin.o] Error 1
make: *** [all] Error 2
```

**Comment by MaxKellermann** [comment]
Oh, I wish there was a way to cross-compile the MacOS build on Linux...

**Comment by ilovezfs** [comment]
You can use Travis CI or our (Homebrew's) CI (with a dummy PR) if you need somewhere to run tests. Or just ask me and I'll do it locally :)

**Comment by MaxKellermann** [comment]
I don't know how that works - commit 4abadc890e3cad81a50630658f642f3ed6944ce1 added a Travis file to master; if you know how to do it, you're very welcome to send a PR with that commit cherry-picked to v0.20.x and additions for Mac support. I'd love to have a systematic solution for that problem.

**Comment by ilovezfs** [comment]
Your patch seems to work!

Here are two examples for adding macOS to Travis:
https://github.com/dunn/homebrew-emacs/blob/master/.travis.yml
https://github.com/OpenLightingProject/ola/blob/master/.travis.yml
