### ISSUE TITLE
MPD 0.21.6 not building on Debian 9

### ISSUE THREAD

**Issue by snake3ca** [MusicPlayerDaemon/MPD#510]
MPD 0.21.6 fails to build on Debian 9.0 

ninja: Entering directory `output/release'
[2/393] Compiling C++ object 'src/even...796227@@event@sta/ServerSocket.cxx.o'.
FAILED: src/event/e796227@@event@sta/ServerSocket.cxx.o 
c++ -Isrc/event/e796227@@event@sta -Isrc/event -I../../src/event -Isrc -I../../src -I. -I../../ -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -O3 -Wall -Wextra -fvisibility=hidden -ffast-math -ftree-vectorize -fno-threadsafe-statics -fmerge-all-constants -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wsign-compare -Wno-non-virtual-dtor -D_GNU_SOURCE -fPIC  -MD -MQ 'src/event/e796227@@event@sta/ServerSocket.cxx.o' -MF 'src/event/e796227@@event@sta/ServerSocket.cxx.o.d' -o 'src/event/e796227@@event@sta/ServerSocket.cxx.o' -c ../../src/event/ServerSocket.cxx
../../src/event/ServerSocket.cxx: In member function ‘void ServerSocket::AddAbstract(const char*)’:
../../src/event/ServerSocket.cxx:409:10: error: ‘class AllocatedSocketAddress’ has no member named ‘SetLocal’; did you mean ‘SetPort’?
  address.SetLocal(name);
          ^~~~~~~~
[3/393] Compiling C++ object 'src/event/e796227@@event@sta/Thread.cxx.o'.
ninja: build stopped: subcommand failed.

**Comment by snake3ca** [comment]
Build only fails with option local_socket set to false in meson_options.txt

option('local_socket', type: 'boolean', value: false, description: 'Support for clients connecting via local sockets')
