### ISSUE TITLE
mpd 0.24.8 don't build with libupnp >= 1.18.0

### ISSUE THREAD

**Issue by 13ilya** [MusicPlayerDaemon/MPD#2440]
## Bug report
mpd 0.24.8 don't build with libupnp >= 1.18.0

## Version
Music Player Daemon 0.24.8 (0.24.8)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2025 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks
................................................

## Configuration
https://build.opensuse.org/package/show/openSUSE:Factory/mpd

## Log
https://build.opensuse.org/build/openSUSE:Factory/standard/x86_64/mpd/_log
```
[   54s] ../src/lib/upnp/ClientInit.cxx: In function â€˜void DoInit()â€™:
[   54s] ../src/lib/upnp/ClientInit.cxx:36:40: error: invalid conversion from â€˜int (*)(Upnp_EventType, const void*, void*) noexceptâ€™ {aka â€˜int (*)(Upnp_EventType_e, const void*, void*) noexceptâ€™} to â€˜Upnp_FunPtrâ€™ {aka â€˜int (*)(Upnp_EventType_e, void*, void*)â€™} [-fpermissive]
[   54s]    36 |         auto code = UpnpRegisterClient(UpnpClientCallback, nullptr,
[   54s]       |                                        ^~~~~~~~~~~~~~~~~~
[   54s]       |                                        |
[   54s]       |                                        int (*)(Upnp_EventType, const void*, void*) noexcept {aka int (*)(Upnp_EventType_e, const void*, void*) noexcept}
[   54s] In file included from ../src/lib/upnp/ClientInit.hxx:6,
[   54s]                  from ../src/lib/upnp/ClientInit.cxx:4:
[   54s] /usr/include/upnp/upnp.h:990:21: note: initializing argument 1 of â€˜int UpnpRegisterClient(Upnp_FunPtr, const void*, UpnpClient_Handle*)â€™
[   54s]   990 |         Upnp_FunPtr Callback,
[   54s]       |         ~~~~~~~~~~~~^~~~~~~~
```

**Comment by MaxKellermann** [comment]
This is a libupnp API breakage, see https://github.com/pupnp/pupnp/issues/528 for my bug report.
MPD starting with 0.24.9 will refuse to build with that version, see commit fd958dfce6c0d75a23b76da460366710eb50302c

This should be fixed by libupnp. I suggest disabling that plugin until a fixed libupnp version becomes available.

**Comment by 13ilya** [comment]
Am I correct in understanding that libupnp version >= 1.14.36 is broken and causes problems, and upstream recommends using libnpupnp instead?

**Comment by MaxKellermann** [comment]
Who is "upstream"?

**Comment by 13ilya** [comment]
Upstream is a community of developers working on a particular project. If you are working on it alone, then you are the upstream developer.

**Comment by MaxKellermann** [comment]
I don't think this phrase makes sense in this context, but I understand what you mean.
If you want my opinion as MPD maintainer on these two libraries, you can see it here: https://github.com/MusicPlayerDaemon/MPD/discussions/1348#discussioncomment-1644297

Since libupnp is currently in a broken state and the maintainer doesn't reply to my bug report, of course I recommend not using that one.

**Comment by 13ilya** [comment]
Great, we understand each other!
As the maintainer of mpd in openSUSE, I already use libnpupnp instead of libupnp.
I wanted to make sure I did the right thing for openSUSE users.

**Comment by MaxKellermann** [comment]
If you maintain packages of MPD, you could improve the quality of that package by explicitly adding all Meson options for each feature you want to have. For example, don't just install `libnpupnp`, also add `-Dupnp=pupnp` to the Meson command line. That way, you make sure this feature really gets enabled. Without this, if the library cannot be found for any reason, MPD will print a warning and then disable the feature; nobody reads that warning, and users may be confused not seeing the feature. With the option, configuring the MPD sources will abort and fail, and this error will be very visible and you'll see and fix the problem quickly.
