### PR TITLE
Implement diacritics stripping and string normalization command

### PR DESCRIPTION
**Pull request by mierak**
Attempt to implement https://github.com/MusicPlayerDaemon/MPD/issues/2327

* Introduces new `stringnormalization` protocol command
* Implements first string normalization to strip diacritics when using `search` and the related commands

The implementation works, but I am unsure whether I took the right approach (and its my first go at CPP). The threading through of booleans is also getting pretty gnarly in there. So I am mostly looking for feedback at this point. We can also workshop the `stringnormalization` name.

### CODE REVIEW

File: src/song/StringFilter.hxx [hunk 1]
```diff
@@ -78,7 +78,7 @@ public:
 	}
 
 	bool GetFoldCase() const noexcept {
-		return fold_case;
+		return icu_compare;
```
[the remark this answers is not in the document]
Comment (mierak) [reply src/song/StringFilter.hxx]: Yup, I missed this one, thanks.

**Comment by MaxKellermann** [comment]
Lots and lots of build failures:
```
../../test/TestStringFilter.cxx: In member function ‘virtual void StringFilterTest_ASCII_Test::TestBody()’:
../../test/TestStringFilter.cxx:23:82: error: no matching function for call to ‘StringFilter::StringFilter(<brace-enclosed initializer list>)’
   23 |         const StringFilter f{"needle", false, StringFilter::Position::FULL, false};
      |                                                                                  ^
```
And some bad coding style, uninitialized variables, .... sigh.

**Comment by MaxKellermann** [comment]
Plus Windows build failures:
```
../../src/lib/icu/Compare.cxx:34:1: error: no declaration matches 'IcuCompare::IcuCompare(std::string_view)'
   34 | IcuCompare::IcuCompare(std::string_view _needle) noexcept
      | ^~~~~~~~~~
```
Same build failure when building without ICU.

When you fix a bad commit, don't add a fixup commit - instead, amend the existing known-bad commit.

**Comment by mierak** [comment]
> Lots and lots of build failures:
> Same build failure when building without ICU.

Compiles for me now both with and without ICU. I have fixed the tests and added a simple test case for diacritic stripping both with and without fold case as well.

> When you fix a bad commit, don't add a fixup commit - instead, amend the existing known-bad commit.

I have squashed them into one since there was already more than one commit.

> Plus Windows build failures

Hopefully should be fine now, but I do not have means to test a windows build atm.

> bad coding style

Not much to go of off here, dev docs state to use spaces, I have tried to follow that as well as to copy the style elsewhere. Im going to need a bit more than "bad"

> uninitialized variables, .... sigh.

Which ones?

**Comment by MaxKellermann** [comment]
> > bad coding style
> 
> Not much to go of off here, dev docs state to use spaces, I have tried to follow that as well as to copy the style elsewhere. Im going to need a bit more than "bad"

Where does it say that?

> > uninitialized variables, .... sigh.
> 
> Which ones?

You added new variables to class IcuCompare, but forgot to initialize them in the copy/move constructors.

File: test/TestStringFilter.cxx [hunk 2]
```diff
@@ -130,17 +130,23 @@ TEST_F(StringFilterTest, Normalize)
...
 {
-	const StringFilter f{"'", true, StringFilter::Position::FULL, false};
+	const StringFilter f{"'", true, false, StringFilter::Position::FULL, false};
 
 	EXPECT_TRUE(f.Match("’"));
 	EXPECT_FALSE(f.Match("\""));
+	EXPECT_TRUE(StringFilter("áéíóúýčďěňřšťžůåäöüàãâçêõîşûğăôơư", true, true, StringFilter::Position::FULL, false)
+            .Match("aeiouycdenrstzuaaouaaaceoisugaoou"));
+	EXPECT_TRUE(StringFilter("ÁÉÍÓÚÝČĎĚŇŘŠŤŽŮÅÄÖÜÀÃÂÇÊÕÎŞÛĞĂÔƠƯ", true, true, StringFilter::Position::FULL, false)
+            .Match("áéíóúýčďěňřšťžůåäöüàãâçêõîşûğăôơư"));
```
Comment (MaxKellermann) [inline test/TestStringFilter.cxx:140]: Bad indent

**Review by MaxKellermann — CHANGES_REQUESTED** [review]
Just ... look at the diff and you see your indentation is all wrong.

**Comment by MaxKellermann** [comment]
> > Plus Windows build failures
> 
> Hopefully should be fine now, but I do not have means to test a windows build atm.

GH Actions disagrees.
```
../src/lib/icu/Compare.cxx: In constructor 'IcuCompare::IcuCompare(std::string_view, bool, bool)':
../src/lib/icu/Compare.cxx:23:41: warning: unused parameter '_needle' [-Wunused-parameter]
   23 | IcuCompare::IcuCompare(std::string_view _needle, bool _fold_case, bool _strip_diacritics) noexcept
      |                        ~~~~~~~~~~~~~~~~~^~~~~~~
../src/lib/icu/Compare.cxx: At global scope:
../src/lib/icu/Compare.cxx:27:1: error: expected unqualified-id before '{' token
   27 | {
      | ^
```

**Comment by mierak** [comment]
> Where does it say that?

I mistyped in a haste, meant to say tabs, sorry.

> Just ... look at the diff and you see your indentation is all wrong.

My apologies, I have misconfigured my editor (only set tabwidth for one file) and my github was on 4 spaces so the diffs looked completely fine to me. Not an excuse, just an explanation. Hopefully they are fine now but tell me if you find any more.

> You added new variables to class IcuCompare, but forgot to initialize them in the copy/move constructors.

I am a bit out of my league here since I am not very familiar with cpp in particular as I have said in the PR description. I have done my reading but am not completely sure I have done the implementation correctly so I would appreciate a feedback on them, thanks!
The bools are initialized in the copy constructors and the move constructor as well and I have attempted to default the source in the latter.

> GH Actions disagrees.

The GH build action now succeeded in my fork I had an extra pair of braces in there.

File: src/lib/icu/Compare.hxx [hunk 3]
```diff
@@ -25,26 +25,54 @@ class IcuCompare {
...
+			: nullptr),
+		 fold_case(src.fold_case),
+		 strip_diacritics(src.strip_diacritics) {}
 
 	IcuCompare &operator=(const IcuCompare &src) noexcept {
 		needle = src
 			? AllocatedString(src.needle)
 			: nullptr;
+        	fold_case = src.fold_case;
+        	strip_diacritics = src.strip_diacritics;
```
[the remark this answers is not in the document]
Comment (mierak) [reply src/lib/icu/Compare.hxx]: fixed

File: src/lib/icu/Compare.hxx [hunk 4]
```diff
@@ -25,26 +25,54 @@ class IcuCompare {
...
+			? AllocatedString(std::move(src.needle))
+			: nullptr;
+		fold_case = src.fold_case;
+		strip_diacritics = src.strip_diacritics;
+
+		src.needle = nullptr;
+		src.fold_case = false;
+		src.strip_diacritics = false;
+		return *this;
+	}
```
Comment (MaxKellermann) [inline src/lib/icu/Compare.hxx:75]: What's the point of this change?

Comment (MaxKellermann) [reply src/lib/icu/Compare.hxx:75]: That comment was wrong, sorry - I meant the copy ctor+operator, not copy+move ctor.
