### PR TITLE
Add openmpt decoder plugin

### PR DESCRIPTION
**Pull request by GrimReaperFloof**
This PR adds the OpenMPT decoder plugin, based on libopenmpt.

Before you merge, I have some questions:
What does `python/build/libs.py` do? Is this a Windows thing where it downloads the libraries, or does it also apply to Unix-based systems?

There's a small amount of code re-use:
```cpp
	const auto buffer = mod_loadfile(nullptr, is);
	if (buffer.IsNull()) {
		LogWarning(openmpt_domain, "could not load stream");
		return false;
	}

	openmpt::module mod(buffer.data, buffer.size);
	delete[] buffer.data;
```
Is there a way to make a function out of it like how it's done in `ModplugDecoderPlugin.cxx`? When I tried I got into problems with returning `openmpt::module` iirc.

Also, are there any memory leaks or memory-related bugs in my code? I'm not that experienced in C/C++. While developing the OpenMPT decoder plugin, I did come across a segmentation fault. I debugged that with gdb and it was at line 155 and 160. After reading the libopenmpt documentation a bit more I figured libopenmpt apparently needs the count to be divided by two. Hence the `OPENMPT_FRAME_SIZE / 2 / sizeof(float)`. Is this fine, or is there any problem with that? Do I need to change anything to the `OPENMPT_FRAME_SIZE` variable? Perhaps integrating the math into it?

In the modplug decoder there's a check for a file being too large. Is that a limitation in libmodplug or is it a limitation in MPD? I left out the file size check in my OpenMPT decoder plugin. Do I need to add it?

Do you have any more suggestions for improving this code?

Also #293 might be somewhat relevant to this PR.

Also, it would be nice if there was a guide on implementing MPD plugins, so the API and how to go about doing things is a bit more clear.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
> This PR adds the OpenMPT decoder plugin, based on libopenmpt.
> 
> Before you merge, I have some questions:
> What does `python/build/libs.py` do? Is this a Windows thing where it downloads the libraries, or does it also apply to Unix-based systems?

It's a kludge that compiles third-party libraries for Windows and Android. There are only declarations; to actually enable a library, add it to `win32/build.py` and `android/build.py`, but only if you believe the plugin is really useful for these platforms.

> Is there a way to make a function out of it like how it's done in `ModplugDecoderPlugin.cxx`? When I tried I got into problems with returning `openmpt::module` iirc.

What kind of problems?

I'll read your code later - but from a first glance, I saw that you copied `mod_loadfile()`, but I don't like code duplication. Maybe a first step would be to move this function to a separate source file, and export it.

> In the modplug decoder there's a check for a file being too large. Is that a limitation in libmodplug or is it a limitation in MPD? I left out the file size check in my OpenMPT decoder plugin. Do I need to add it?

It's a limitation of everybody's computer! Imagine you have a file weighing 100 Petabytes, and then imagine MPD asking the operating system to allocate this amount of RAM. There must be a limit. The current one is arbitrary.

> Also, it would be nice if there was a guide on implementing MPD plugins, so the API and how to go about doing things is a bit more clear.

... it would be nice if somebody wrote a guide after writing such a plugin!

**Comment by GrimReaperFloof** [comment]
> It's a limitation of everybody's computer! Imagine you have a file weighing 100 Petabytes, and then imagine MPD asking the operating system to allocate this amount of RAM. There must be a limit. The current one is arbitrary.

Why add an arbitrary limit though? What if someone does in fact have petabytes of RAM?

**Comment by MaxKellermann** [comment]
That's why the limit is low enough to avoid overloading anybody's computer, but still high enough that nobody has ever complained, ever.
An advanced approach to this problem could be memory-mapping the file, and let the kernel manage the allocations.

Answering your question "why" - because that's how this code was written, it proved to just work, nobody had a problem, and so there was no pain for anybody to engineer a better solution.

**Comment by GrimReaperFloof** [comment]
Alright, I moved the `mod_loadfile()` function to a separate source file.

```cpp
	const auto buffer = mod_loadfile(nullptr, is);
	if (buffer.IsNull()) {
		LogWarning(openmpt_domain, "could not load stream");
		return false;
	}

	openmpt::module mod(buffer.data, buffer.size);
	delete[] buffer.data;
```
I was still unable to do something about the above code I was talking about earlier. If I want to put that into a function I might have to return a pointer, although when I tried, it gave me a warning and the openmpt decoder plugin broke after compiling. Probably because the pointer would become invalid as it leaves the scope. Maybe I need to use malloc? I'm not sure about how to get the size of openmpt modules in order to do that. I have never used malloc before.
But to be honest, this isn't so bad. It's only 6 lines of code and the return values slightly differ between the functions. In `ModplugDecoderPlugin.cxx` this code is offloaded to another function, but when calling that function from the other functions, it still needs an if statement to check if it returned a nullptr. Kinda similar to how it checks for `buffer.isNull` in my code. The only real thing a separate function for this would abstract away would be `delete[] buffer.data;`. So I don't think this is really that big of a deal. What do you think?

**Comment by MaxKellermann** [comment]
I have no idea what you mean, and what broke.
No, you don't need `malloc()`. Never use it.
(Actually you should also never use `new` and `delete` - the existing Modplug plugin isn't so good. This code isn't exception-safe; it's always better to use smart pointers in C++. For example, MPD has the `AllocatedArray` class which automatically frees the allocated memory, and remembers the size. The LoadFile function could return `AllocatedArray<std::byte>`.)

**Comment by GrimReaperFloof** [comment]
Is this alright? Did I use AllocatedArray correctly? Any more suggestions?

**Comment by GrimReaperFloof** [comment]
Also is it possible to use DecoderPlugin.WithContainer with an InputStream instead of a Path?
Or should I just use Path if I want to use containers?

**Comment by MaxKellermann** [comment]
> Also is it possible to use DecoderPlugin.WithContainer with an InputStream instead of a Path?
> Or should I just use Path if I want to use containers?

The API currently supports only local files. This should be improved (and you're welcome to help), but that's how it is currently.
(I'll review your code later - sorry for the delay, dayjob is nagging)

**Comment by GrimReaperFloof** [comment]
Should I in the meantime prefer implementing InputStream and not support subsongs? Or should I implement Path and support subsongs?

**Comment by GrimReaperFloof** [comment]
I have just pushed a version of the openmpt decoder plugin that uses Path and supports subsongs on the `add-openmpt-decoder_Path-version` branch on my MPD fork repository.

**Comment by GrimReaperFloof** [comment]
Actually InputStream should be preferred yeah. Path can't handle files inside archives. After all, subsongs isn't used a lot in modules, and the majority of cases a subsong is found, it's a duplicate of the song or a small part of it. But I do know of some modules that make legitimate use of subsongs. But I don't think the positives of subsongs outweigh the negatives of using Path. I guess I'll implement subsongs when WithContainer supports InputStream.

**Comment by MaxKellermann** [comment]
Doesn't compile:
```
../../src/decoder/plugins/OpenmptDecoderPlugin.cxx: In function ‘void mod_decode(DecoderClient&, InputStream&)’:
../../src/decoder/plugins/OpenmptDecoderPlugin.cxx:86:6: error: ‘class openmpt::module’ has no member named ‘ctl_set_boolean’
   86 |  mod.ctl_set_boolean("seek.sync_samples", openmpt_sync_samples);
      |      ^~~~~~~~~~~~~~~
../../src/decoder/plugins/OpenmptDecoderPlugin.cxx:87:6: error: ‘class openmpt::module’ has no member named ‘ctl_set_boolean’
   87 |  mod.ctl_set_boolean("render.resampler.emulate_amiga", openmpt_emulate_amiga);
      |      ^~~~~~~~~~~~~~~
../../src/decoder/plugins/OpenmptDecoderPlugin.cxx:88:6: error: ‘class openmpt::module’ has no member named ‘ctl_set_text’
   88 |  mod.ctl_set_text("render.resampler.emulate_amiga_type", openmpt_emulate_amiga_type);
      |      ^~~~~~~~~~~~
```

**Comment by MaxKellermann** [comment]
I've cherry-picked the last two patches (refactoring); please rebase your PR branch and resolve the conflicts.

**Comment by GrimReaperFloof** [comment]
> Doesn't compile:
> 
> ```
> ../../src/decoder/plugins/OpenmptDecoderPlugin.cxx: In function ‘void mod_decode(DecoderClient&, InputStream&)’:
> ../../src/decoder/plugins/OpenmptDecoderPlugin.cxx:86:6: error: ‘class openmpt::module’ has no member named ‘ctl_set_boolean’
>    86 |  mod.ctl_set_boolean("seek.sync_samples", openmpt_sync_samples);
>       |      ^~~~~~~~~~~~~~~
> ../../src/decoder/plugins/OpenmptDecoderPlugin.cxx:87:6: error: ‘class openmpt::module’ has no member named ‘ctl_set_boolean’
>    87 |  mod.ctl_set_boolean("render.resampler.emulate_amiga", openmpt_emulate_amiga);
>       |      ^~~~~~~~~~~~~~~
> ../../src/decoder/plugins/OpenmptDecoderPlugin.cxx:88:6: error: ‘class openmpt::module’ has no member named ‘ctl_set_text’
>    88 |  mod.ctl_set_text("render.resampler.emulate_amiga_type", openmpt_emulate_amiga_type);
>       |      ^~~~~~~~~~~~
> ```

Strange. What libopenmpt version did you use? I was using 0.5.8 while developing the plugin.

**Comment by GrimReaperFloof** [comment]
I see those functions are only available since libopenmpt 0.5.0. Should I add version checks and call the appropriate functions?

**Comment by MaxKellermann** [comment]
Yes, if you know a certain version is required, it should be part of the dependency check in the Meson file.

**Comment by GrimReaperFloof** [comment]
I see some other decoder plugins like GME and Wildmidi have some version checking using the preprocessor. Do you have any idea how I could do this in libopenmpt? To get the library version you have to call `openmpt::get_library_version()`, but this is not a constant expression so I don't think I can use it in the preprocessor. I just tried this and it does compile but it never runs the code I want it to even if the version is over 0x50000. And if I just do an if-statement in normal C++, it won't compile with libopenmpt 0.4 like in your case. Do you have any idea what I can do? There seems to be a preprocessor variable called OPENMPT_STRING_LIBRARY_VERSION, but in the libopenmpt documentation it says this is deprecated. Is there something I can do with Meson perhaps?

**Comment by GrimReaperFloof** [comment]
Okay so I just added some thing to the meson.build to set `HAVE_LIBOPENMPT_VERSION_0_5` when the version of libopenmpt is greater than 0.5, but there's a problem. It never executes the code for libopenmpt versions 0.5 and above.
I have checked the Meson manual and I believe I'm doing everything right here, yet it still doesn't work.
`libopenmpt_dep.version().version_compare('>= 0.5')` does return `True`. I have checked using a `message()` but for some reason it never runs the code I want it to.
Do you have any idea what's going on?

**Comment by dgcampea** [comment]
> Okay so I just added some thing to the meson.build to set `HAVE_LIBOPENMPT_VERSION_0_5` when the version of libopenmpt is greater than 0.5, but there's a problem. It never executes the code for libopenmpt versions 0.5 and above.
> I have checked the Meson manual and I believe I'm doing everything right here, yet it still doesn't work.
> `libopenmpt_dep.version().version_compare('>= 0.5')` does return `True`. I have checked using a `message()` but for some reason it never runs the code I want it to when I build using libopenmpt 0.5.
> Do you have any idea what's going on?

Not a meson expert but you need to add `#include "decoder/Features.h"` to `src/decoder/plugins/OpenmptDecoderPlugin.cxx` according to <https://mesonbuild.com/Configuration.html#a-full-example>.

**Comment by GrimReaperFloof** [comment]
@dgcampea Wow, that worked! Thanks! I have added the `decoder/Features.h` import and `git commit --amend`ed it as broken commits don't look very good in the history imo.

**Comment by GrimReaperFloof** [comment]
That was a rebase

**Comment by MaxKellermann** [comment]
Doesn't compile:
```../../src/decoder/plugins/OpenmptDecoderPlugin.cxx: In function ‘void mod_decode(DecoderClient&, InputStream&)’:
../../src/decoder/plugins/OpenmptDecoderPlugin.cxx:99:70: error: passing ‘bool’ chooses ‘int’ over ‘unsigned int’ [-Werror=sign-promo]
   99 |  mod.ctl_set("seek.sync_samples", std::to_string(openmpt_sync_samples));
      |                                                                      ^
../../src/decoder/plugins/OpenmptDecoderPlugin.cxx:99:70: error:   in call to ‘std::string std::__cxx11::to_string(int)’ [-Werror=sign-promo]
../../src/decoder/plugins/OpenmptDecoderPlugin.cxx:100:84: error: passing ‘bool’ chooses ‘int’ over ‘unsigned int’ [-Werror=sign-promo]
  100 |  mod.ctl_set("render.resampler.emulate_amiga", std::to_string(openmpt_emulate_amiga));
      |                                                                                    ^
../../src/decoder/plugins/OpenmptDecoderPlugin.cxx:100:84: error:   in call to ‘std::string std::__cxx11::to_string(int)’ [-Werror=sign-promo]
```
```

**Comment by GrimReaperFloof** [comment]
> Doesn't compile:
> 
> ```
> ../../src/decoder/plugins/OpenmptDecoderPlugin.cxx:99:70: error: passing ‘bool’ chooses ‘int’ over ‘unsigned int’ [-Werror=sign-promo]
>    99 |  mod.ctl_set("seek.sync_samples", std::to_string(openmpt_sync_samples));
>       |                                                                      ^
> ../../src/decoder/plugins/OpenmptDecoderPlugin.cxx:99:70: error:   in call to ‘std::string std::__cxx11::to_string(int)’ [-Werror=sign-promo]
> ../../src/decoder/plugins/OpenmptDecoderPlugin.cxx:100:84: error: passing ‘bool’ chooses ‘int’ over ‘unsigned int’ [-Werror=sign-promo]
>   100 |  mod.ctl_set("render.resampler.emulate_amiga", std::to_string(openmpt_emulate_amiga));
>       |                                                                                    ^
> ../../src/decoder/plugins/OpenmptDecoderPlugin.cxx:100:84: error:   in call to ‘std::string std::__cxx11::to_string(int)’ [-Werror=sign-promo]
> ```
Huh. I can reproduce it on libopenmpt 0.3 but for me they're only warnings, and compilation continues without further issues. How should I solve this anyway? Casting to unsinged int?

**Comment by GrimReaperFloof** [comment]
Hopefully this fixes it. I don't see the warning anymore now.
