### ISSUE TITLE
`mpd-0.23.15` does not build with `fmt-11.0.2`

### ISSUE THREAD

**Issue by cuantar** [MusicPlayerDaemon/MPD#2141]
### Describe the bug
Updated `fmt` to `11.0.2` and discovered that `mpd` cannot compile.

## Expected Behavior
Package compiles successfully.

## Actual Behavior
Compilation fails.  From the build log:
```
/usr/include/fmt/base.h:1402:29: error: passing ‘const fmt::v11::formatter<std::__exception_ptr::exception_ptr>’ as ‘this’ argument discards qualifiers [-fpermissive]
 1402 |     ctx.advance_to(cf.format(*static_cast<qualified_type*>(arg), ctx));
      |                    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
